// Static seed checklists used when opening a trailer shift. Pure data, server-only.

export const TEMPLATES = {
  opening: [
    { section: "OPEN + POWER ON",   title: "Open trailer",                       assignee_role: "shift_lead", requires_signoff: false },
    { section: "OPEN + POWER ON",   title: "Turn on lights",                     assignee_role: "shift_lead", requires_signoff: false },
    { section: "OPEN + POWER ON",   title: "Turn on propane valves",             assignee_role: "shift_lead", requires_signoff: true  },
    { section: "OPEN + POWER ON",   title: "Turn on grills",                     assignee_role: "grill",      requires_signoff: false },
    { section: "OPEN + POWER ON",   title: "Turn on deep fryers",                assignee_role: "grill",      requires_signoff: false },
    { section: "TRAY + STATION",    title: "Check all trays and stations for prep needs", assignee_role: "prep", requires_signoff: false },
    { section: "OPENING SIGN-OFF",  title: "Trailer open and ready",             assignee_role: "shift_lead", requires_signoff: true  },
    { section: "OPENING SIGN-OFF",  title: "Lights on",                          assignee_role: "shift_lead", requires_signoff: false },
    { section: "OPENING SIGN-OFF",  title: "Propane on",                         assignee_role: "shift_lead", requires_signoff: true  },
    { section: "OPENING SIGN-OFF",  title: "Grill heating",                      assignee_role: "grill",      requires_signoff: false },
    { section: "OPENING SIGN-OFF",  title: "Fryers heating",                     assignee_role: "grill",      requires_signoff: false },
    { section: "OPENING SIGN-OFF",  title: "Prep list identified",               assignee_role: "shift_lead", requires_signoff: true  },
  ],
  mid: [
    { section: "TRAY CHECK + SETUP",  title: "Check all trays",                            assignee_role: "prep", requires_signoff: false },
    { section: "TRAY CHECK + SETUP",  title: "Organize prep priorities",                   assignee_role: "prep", requires_signoff: false },
    { section: "BACON + ONION PREP",  title: "Cut bacon in half",                          assignee_role: "prep", requires_signoff: false },
    { section: "BACON + ONION PREP",  title: "Start bacon on grill",                       assignee_role: "grill", requires_signoff: false },
    { section: "BACON + ONION PREP",  title: "Fill bacon trays to par — 2 full trays",     assignee_role: "prep", requires_signoff: false },
    { section: "BACON + ONION PREP",  title: "Fill onion trays to par — 2 full trays",     assignee_role: "prep", requires_signoff: false },
    { section: "LETTUCE + JALAPEÑO",  title: "Cut 4 heads of lettuce",                     assignee_role: "prep", requires_signoff: false },
    { section: "LETTUCE + JALAPEÑO",  title: "Put lettuce in quarter tray — 1 quarter tray", assignee_role: "prep", requires_signoff: false },
    { section: "LETTUCE + JALAPEÑO",  title: "Cut 2 bags of jalapeños",                    assignee_role: "prep", requires_signoff: false },
    { section: "LETTUCE + JALAPEÑO",  title: "Put jalapeños in tray — 1.5 full trays",     assignee_role: "prep", requires_signoff: false },
    { section: "GROUND BEEF PREP",    title: "Check ground beef inventory — 4–5 full trays", assignee_role: "grill", requires_signoff: false },
    { section: "GROUND BEEF PREP",    title: "Take out 2 bags of ground beef",             assignee_role: "grill", requires_signoff: false },
    { section: "GROUND BEEF PREP",    title: "Cook ground beef to 80–90%",                 assignee_role: "grill", requires_signoff: true  },
    { section: "GROUND BEEF PREP",    title: "Leave a little juice in beef",               assignee_role: "grill", requires_signoff: false },
    { section: "GROUND BEEF PREP",    title: "Put cooked beef into 2 half trays",          assignee_role: "grill", requires_signoff: false },
    { section: "SAUCE + CONDIMENT",   title: "Fill 32 oz sauce bottles — 10–12 filled",    assignee_role: "prep", requires_signoff: false },
    { section: "SAUCE + CONDIMENT",   title: "Fill small sauce containers",                assignee_role: "prep", requires_signoff: false },
    { section: "SAUCE + CONDIMENT",   title: "Fill 1 full tray of container sauces",       assignee_role: "prep", requires_signoff: false },
    { section: "SAUCE + CONDIMENT",   title: "Fill 1 quarter tray of ketchup containers",  assignee_role: "prep", requires_signoff: false },
    { section: "DISHES + RESET",      title: "Wash dishes as needed",                      assignee_role: "prep", requires_signoff: false },
    { section: "DISHES + RESET",      title: "Clean and tidy workspace",                   assignee_role: "prep", requires_signoff: false },
    { section: "PREP PAR SIGN-OFF",   title: "Bacon = 2 full trays",                       assignee_role: "shift_lead", requires_signoff: true },
    { section: "PREP PAR SIGN-OFF",   title: "Onions = 2 full trays",                      assignee_role: "shift_lead", requires_signoff: true },
    { section: "PREP PAR SIGN-OFF",   title: "Lettuce = 1 quarter tray",                   assignee_role: "shift_lead", requires_signoff: true },
    { section: "PREP PAR SIGN-OFF",   title: "Jalapeños = 1.5 full trays",                 assignee_role: "shift_lead", requires_signoff: true },
    { section: "PREP PAR SIGN-OFF",   title: "Ground beef = 4–5 full trays",               assignee_role: "shift_lead", requires_signoff: true },
    { section: "PREP PAR SIGN-OFF",   title: "Cooked ground beef = 2 half trays",          assignee_role: "shift_lead", requires_signoff: true },
    { section: "PREP PAR SIGN-OFF",   title: "Sauce bottles = 10–12 filled",               assignee_role: "shift_lead", requires_signoff: true },
    { section: "PREP PAR SIGN-OFF",   title: "Container sauces = 1 full tray",             assignee_role: "shift_lead", requires_signoff: true },
    { section: "PREP PAR SIGN-OFF",   title: "Ketchup containers = 1 quarter tray",        assignee_role: "shift_lead", requires_signoff: true },
    { section: "PREP PAR SIGN-OFF",   title: "Dishes handled",                             assignee_role: "shift_lead", requires_signoff: false },
    { section: "PREP PAR SIGN-OFF",   title: "Workspace shift-ready",                      assignee_role: "shift_lead", requires_signoff: true },
  ],
  closing: [
    { section: "SHUTDOWN EQUIPMENT",  title: "Turn off both grills",                       assignee_role: "grill",      requires_signoff: true  },
    { section: "SHUTDOWN EQUIPMENT",  title: "Turn off deep fryers",                       assignee_role: "grill",      requires_signoff: true  },
    { section: "SHUTDOWN EQUIPMENT",  title: "Turn off steam table from knobs",            assignee_role: "grill",      requires_signoff: true  },
    { section: "CLEAN + COVER",       title: "Clean workstations",                         assignee_role: "prep",       requires_signoff: false },
    { section: "CLEAN + COVER",       title: "Cover all vegetables and meat",              assignee_role: "prep",       requires_signoff: true  },
    { section: "NEXT-DAY MEAT PULL",  title: "Pull ground beef from freezer — 20–25 bags (4 bags = 1 tray)", assignee_role: "grill", requires_signoff: true },
    { section: "NEXT-DAY MEAT PULL",  title: "Pull bacon from freezer — 2–3 bags",         assignee_role: "grill",      requires_signoff: true  },
    { section: "NEXT-DAY MEAT PULL",  title: "Move ground beef & bacon to fridge if weather is warm", assignee_role: "grill", requires_signoff: false },
    { section: "DISHES + SINKS",      title: "Wash all dishes",                            assignee_role: "prep",       requires_signoff: false },
    { section: "DISHES + SINKS",      title: "Clean sinks",                                assignee_role: "prep",       requires_signoff: false },
    { section: "FLOORS + TRASH",      title: "Sweep floors",                               assignee_role: "prep",       requires_signoff: false },
    { section: "FLOORS + TRASH",      title: "Take out mats and remove debris",            assignee_role: "prep",       requires_signoff: false },
    { section: "FLOORS + TRASH",      title: "Remove all filled garbage bags",             assignee_role: "prep",       requires_signoff: false },
    { section: "FLOORS + TRASH",      title: "Install new empty garbage bags",             assignee_role: "prep",       requires_signoff: false },
    { section: "FLOORS + TRASH",      title: "Throw discarded boxes in dumpster",          assignee_role: "prep",       requires_signoff: false },
    { section: "FINAL READINESS",     title: "Check inventory for next day",               assignee_role: "shift_lead", requires_signoff: true  },
    { section: "FINAL READINESS",     title: "Ensure enough 6QT sauce buckets",            assignee_role: "shift_lead", requires_signoff: false },
    { section: "FINAL READINESS",     title: "Plug work phone into charger",               assignee_role: "shift_lead", requires_signoff: false },
    { section: "FINAL READINESS",     title: "Plug wireless card reader into charger",     assignee_role: "shift_lead", requires_signoff: false },
    { section: "FINAL READINESS",     title: "Trailer ready for next day",                 assignee_role: "shift_lead", requires_signoff: true  },
    { section: "CLOSING SIGN-OFF",    title: "Grills off",                                 assignee_role: "shift_lead", requires_signoff: true  },
    { section: "CLOSING SIGN-OFF",    title: "Fryers off",                                 assignee_role: "shift_lead", requires_signoff: true  },
    { section: "CLOSING SIGN-OFF",    title: "Steam table off",                            assignee_role: "shift_lead", requires_signoff: true  },
    { section: "CLOSING SIGN-OFF",    title: "Workstations cleaned",                       assignee_role: "shift_lead", requires_signoff: false },
    { section: "CLOSING SIGN-OFF",    title: "Vegetables & meat covered",                  assignee_role: "shift_lead", requires_signoff: true  },
    { section: "CLOSING SIGN-OFF",    title: "Ground beef pulled — 20–25 bags",            assignee_role: "shift_lead", requires_signoff: true  },
    { section: "CLOSING SIGN-OFF",    title: "Bacon pulled — 2–3 bags",                    assignee_role: "shift_lead", requires_signoff: true  },
    { section: "CLOSING SIGN-OFF",    title: "Dishes washed, sinks cleaned",               assignee_role: "shift_lead", requires_signoff: false },
    { section: "CLOSING SIGN-OFF",    title: "Floors swept, mats cleaned",                 assignee_role: "shift_lead", requires_signoff: false },
    { section: "CLOSING SIGN-OFF",    title: "Trash removed, new bags installed",          assignee_role: "shift_lead", requires_signoff: false },
    { section: "CLOSING SIGN-OFF",    title: "Boxes discarded",                            assignee_role: "shift_lead", requires_signoff: false },
    { section: "CLOSING SIGN-OFF",    title: "Inventory checked, 6QT buckets stocked",     assignee_role: "shift_lead", requires_signoff: true  },
    { section: "CLOSING SIGN-OFF",    title: "Trailer ready for next day",                 assignee_role: "shift_lead", requires_signoff: true  },
  ],
  emergency: [
    { section: "INVENTORY SIGN-OFF",       title: "Vegetables/perishables at min stock",   assignee_role: "manager",    requires_signoff: true  },
    { section: "INVENTORY SIGN-OFF",       title: "Meats at min stock",                    assignee_role: "manager",    requires_signoff: true  },
    { section: "INVENTORY SIGN-OFF",       title: "Sauces at min stock",                   assignee_role: "manager",    requires_signoff: true  },
    { section: "INVENTORY SIGN-OFF",       title: "Takeout containers/supplies at min",    assignee_role: "manager",    requires_signoff: true  },
    { section: "INVENTORY SIGN-OFF",       title: "Low items identified",                  assignee_role: "manager",    requires_signoff: true  },
    { section: "INVENTORY SIGN-OFF",       title: "Restock needs noted",                   assignee_role: "manager",    requires_signoff: true  },
  ],
} as const;
