/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as UsersRouteImport } from './routes/users'
import { Route as SopsRouteImport } from './routes/sops'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as ScheduleRouteImport } from './routes/schedule'
import { Route as RoleRouteImport } from './routes/role'
import { Route as PermissionsRouteImport } from './routes/permissions'
import { Route as OperationsRouteImport } from './routes/operations'
import { Route as MyTasksRouteImport } from './routes/my-tasks'
import { Route as ManagerRouteImport } from './routes/manager'
import { Route as InventoryRouteImport } from './routes/inventory'
import { Route as HospitalityRouteImport } from './routes/hospitality'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuditRouteImport } from './routes/audit'
import { Route as AnalyticsRouteImport } from './routes/analytics'
import { Route as IndexRouteImport } from './routes/index'

const UsersRoute = UsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => rootRouteImport,
} as any)
const SopsRoute = SopsRouteImport.update({
  id: '/sops',
  path: '/sops',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const ScheduleRoute = ScheduleRouteImport.update({
  id: '/schedule',
  path: '/schedule',
  getParentRoute: () => rootRouteImport,
} as any)
const RoleRoute = RoleRouteImport.update({
  id: '/role',
  path: '/role',
  getParentRoute: () => rootRouteImport,
} as any)
const PermissionsRoute = PermissionsRouteImport.update({
  id: '/permissions',
  path: '/permissions',
  getParentRoute: () => rootRouteImport,
} as any)
const OperationsRoute = OperationsRouteImport.update({
  id: '/operations',
  path: '/operations',
  getParentRoute: () => rootRouteImport,
} as any)
const MyTasksRoute = MyTasksRouteImport.update({
  id: '/my-tasks',
  path: '/my-tasks',
  getParentRoute: () => rootRouteImport,
} as any)
const ManagerRoute = ManagerRouteImport.update({
  id: '/manager',
  path: '/manager',
  getParentRoute: () => rootRouteImport,
} as any)
const InventoryRoute = InventoryRouteImport.update({
  id: '/inventory',
  path: '/inventory',
  getParentRoute: () => rootRouteImport,
} as any)
const HospitalityRoute = HospitalityRouteImport.update({
  id: '/hospitality',
  path: '/hospitality',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuditRoute = AuditRouteImport.update({
  id: '/audit',
  path: '/audit',
  getParentRoute: () => rootRouteImport,
} as any)
const AnalyticsRoute = AnalyticsRouteImport.update({
  id: '/analytics',
  path: '/analytics',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/analytics': typeof AnalyticsRoute
  '/audit': typeof AuditRoute
  '/auth': typeof AuthRoute
  '/hospitality': typeof HospitalityRoute
  '/inventory': typeof InventoryRoute
  '/manager': typeof ManagerRoute
  '/my-tasks': typeof MyTasksRoute
  '/operations': typeof OperationsRoute
  '/permissions': typeof PermissionsRoute
  '/role': typeof RoleRoute
  '/schedule': typeof ScheduleRoute
  '/settings': typeof SettingsRoute
  '/sops': typeof SopsRoute
  '/users': typeof UsersRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/analytics': typeof AnalyticsRoute
  '/audit': typeof AuditRoute
  '/auth': typeof AuthRoute
  '/hospitality': typeof HospitalityRoute
  '/inventory': typeof InventoryRoute
  '/manager': typeof ManagerRoute
  '/my-tasks': typeof MyTasksRoute
  '/operations': typeof OperationsRoute
  '/permissions': typeof PermissionsRoute
  '/role': typeof RoleRoute
  '/schedule': typeof ScheduleRoute
  '/settings': typeof SettingsRoute
  '/sops': typeof SopsRoute
  '/users': typeof UsersRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/analytics': typeof AnalyticsRoute
  '/audit': typeof AuditRoute
  '/auth': typeof AuthRoute
  '/hospitality': typeof HospitalityRoute
  '/inventory': typeof InventoryRoute
  '/manager': typeof ManagerRoute
  '/my-tasks': typeof MyTasksRoute
  '/operations': typeof OperationsRoute
  '/permissions': typeof PermissionsRoute
  '/role': typeof RoleRoute
  '/schedule': typeof ScheduleRoute
  '/settings': typeof SettingsRoute
  '/sops': typeof SopsRoute
  '/users': typeof UsersRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/analytics'
    | '/audit'
    | '/auth'
    | '/hospitality'
    | '/inventory'
    | '/manager'
    | '/my-tasks'
    | '/operations'
    | '/permissions'
    | '/role'
    | '/schedule'
    | '/settings'
    | '/sops'
    | '/users'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/analytics'
    | '/audit'
    | '/auth'
    | '/hospitality'
    | '/inventory'
    | '/manager'
    | '/my-tasks'
    | '/operations'
    | '/permissions'
    | '/role'
    | '/schedule'
    | '/settings'
    | '/sops'
    | '/users'
  id:
    | '__root__'
    | '/'
    | '/analytics'
    | '/audit'
    | '/auth'
    | '/hospitality'
    | '/inventory'
    | '/manager'
    | '/my-tasks'
    | '/operations'
    | '/permissions'
    | '/role'
    | '/schedule'
    | '/settings'
    | '/sops'
    | '/users'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AnalyticsRoute: typeof AnalyticsRoute
  AuditRoute: typeof AuditRoute
  AuthRoute: typeof AuthRoute
  HospitalityRoute: typeof HospitalityRoute
  InventoryRoute: typeof InventoryRoute
  ManagerRoute: typeof ManagerRoute
  MyTasksRoute: typeof MyTasksRoute
  OperationsRoute: typeof OperationsRoute
  PermissionsRoute: typeof PermissionsRoute
  RoleRoute: typeof RoleRoute
  ScheduleRoute: typeof ScheduleRoute
  SettingsRoute: typeof SettingsRoute
  SopsRoute: typeof SopsRoute
  UsersRoute: typeof UsersRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/users': {
      id: '/users'
      path: '/users'
      fullPath: '/users'
      preLoaderRoute: typeof UsersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sops': {
      id: '/sops'
      path: '/sops'
      fullPath: '/sops'
      preLoaderRoute: typeof SopsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/schedule': {
      id: '/schedule'
      path: '/schedule'
      fullPath: '/schedule'
      preLoaderRoute: typeof ScheduleRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/role': {
      id: '/role'
      path: '/role'
      fullPath: '/role'
      preLoaderRoute: typeof RoleRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/permissions': {
      id: '/permissions'
      path: '/permissions'
      fullPath: '/permissions'
      preLoaderRoute: typeof PermissionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/operations': {
      id: '/operations'
      path: '/operations'
      fullPath: '/operations'
      preLoaderRoute: typeof OperationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/my-tasks': {
      id: '/my-tasks'
      path: '/my-tasks'
      fullPath: '/my-tasks'
      preLoaderRoute: typeof MyTasksRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/manager': {
      id: '/manager'
      path: '/manager'
      fullPath: '/manager'
      preLoaderRoute: typeof ManagerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/inventory': {
      id: '/inventory'
      path: '/inventory'
      fullPath: '/inventory'
      preLoaderRoute: typeof InventoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/hospitality': {
      id: '/hospitality'
      path: '/hospitality'
      fullPath: '/hospitality'
      preLoaderRoute: typeof HospitalityRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/audit': {
      id: '/audit'
      path: '/audit'
      fullPath: '/audit'
      preLoaderRoute: typeof AuditRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/analytics': {
      id: '/analytics'
      path: '/analytics'
      fullPath: '/analytics'
      preLoaderRoute: typeof AnalyticsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AnalyticsRoute: AnalyticsRoute,
  AuditRoute: AuditRoute,
  AuthRoute: AuthRoute,
  HospitalityRoute: HospitalityRoute,
  InventoryRoute: InventoryRoute,
  ManagerRoute: ManagerRoute,
  MyTasksRoute: MyTasksRoute,
  OperationsRoute: OperationsRoute,
  PermissionsRoute: PermissionsRoute,
  RoleRoute: RoleRoute,
  ScheduleRoute: ScheduleRoute,
  SettingsRoute: SettingsRoute,
  SopsRoute: SopsRoute,
  UsersRoute: UsersRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
