/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as UsersRouteImport } from './routes/users'
import { Route as TimeClockRouteImport } from './routes/time-clock'
import { Route as SopsRouteImport } from './routes/sops'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as ScheduleRouteImport } from './routes/schedule'
import { Route as RoleRouteImport } from './routes/role'
import { Route as RecapsRouteImport } from './routes/recaps'
import { Route as PrepLogRouteImport } from './routes/prep-log'
import { Route as PermissionsRouteImport } from './routes/permissions'
import { Route as OrderGuideRouteImport } from './routes/order-guide'
import { Route as OperationsRouteImport } from './routes/operations'
import { Route as MyTasksRouteImport } from './routes/my-tasks'
import { Route as ManagerRouteImport } from './routes/manager'
import { Route as LocationRequestsRouteImport } from './routes/location-requests'
import { Route as LaborRouteImport } from './routes/labor'
import { Route as InventoryGuideRouteImport } from './routes/inventory-guide'
import { Route as InventoryChangesRouteImport } from './routes/inventory-changes'
import { Route as InventoryRouteImport } from './routes/inventory'
import { Route as IntegrityRouteImport } from './routes/integrity'
import { Route as HrDocumentsRouteImport } from './routes/hr-documents'
import { Route as HospitalityRouteImport } from './routes/hospitality'
import { Route as HealthRouteImport } from './routes/health'
import { Route as HandbookRouteImport } from './routes/handbook'
import { Route as EmailLogRouteImport } from './routes/email-log'
import { Route as DataHealthRouteImport } from './routes/data-health'
import { Route as ChangeLogRouteImport } from './routes/change-log'
import { Route as CashRouteImport } from './routes/cash'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuditRouteImport } from './routes/audit'
import { Route as ArchiveCenterRouteImport } from './routes/archive-center'
import { Route as AnalyticsRouteImport } from './routes/analytics'
import { Route as AlertsRouteImport } from './routes/alerts'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as IndexRouteImport } from './routes/index'
import { Route as EmailUnsubscribeRouteImport } from './routes/email/unsubscribe'
import { Route as LovableEmailSuppressionRouteImport } from './routes/lovable/email/suppression'
import { Route as LovableEmailTransactionalSendRouteImport } from './routes/lovable/email/transactional/send'
import { Route as LovableEmailTransactionalPreviewRouteImport } from './routes/lovable/email/transactional/preview'
import { Route as LovableEmailQueueProcessRouteImport } from './routes/lovable/email/queue/process'
import { Route as LovableEmailAuthWebhookRouteImport } from './routes/lovable/email/auth/webhook'
import { Route as LovableEmailAuthPreviewRouteImport } from './routes/lovable/email/auth/preview'
import { Route as ApiPublicHooksEmailQaSelftestRouteImport } from './routes/api/public/hooks/email-qa-selftest'
import { Route as ApiPublicHooksDailyRolloverRouteImport } from './routes/api/public/hooks/daily-rollover'
import { Route as ApiPublicHooksDailyDigestRouteImport } from './routes/api/public/hooks/daily-digest'
import { Route as ApiPublicHooksArchivePurgeRouteImport } from './routes/api/public/hooks/archive-purge'
import { Route as ApiPublicHooksAlertEmailDispatchRouteImport } from './routes/api/public/hooks/alert-email-dispatch'

const UsersRoute = UsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => rootRouteImport,
} as any)
const TimeClockRoute = TimeClockRouteImport.update({
  id: '/time-clock',
  path: '/time-clock',
  getParentRoute: () => rootRouteImport,
} as any)
const SopsRoute = SopsRouteImport.update({
  id: '/sops',
  path: '/sops',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const ScheduleRoute = ScheduleRouteImport.update({
  id: '/schedule',
  path: '/schedule',
  getParentRoute: () => rootRouteImport,
} as any)
const RoleRoute = RoleRouteImport.update({
  id: '/role',
  path: '/role',
  getParentRoute: () => rootRouteImport,
} as any)
const RecapsRoute = RecapsRouteImport.update({
  id: '/recaps',
  path: '/recaps',
  getParentRoute: () => rootRouteImport,
} as any)
const PrepLogRoute = PrepLogRouteImport.update({
  id: '/prep-log',
  path: '/prep-log',
  getParentRoute: () => rootRouteImport,
} as any)
const PermissionsRoute = PermissionsRouteImport.update({
  id: '/permissions',
  path: '/permissions',
  getParentRoute: () => rootRouteImport,
} as any)
const OrderGuideRoute = OrderGuideRouteImport.update({
  id: '/order-guide',
  path: '/order-guide',
  getParentRoute: () => rootRouteImport,
} as any)
const OperationsRoute = OperationsRouteImport.update({
  id: '/operations',
  path: '/operations',
  getParentRoute: () => rootRouteImport,
} as any)
const MyTasksRoute = MyTasksRouteImport.update({
  id: '/my-tasks',
  path: '/my-tasks',
  getParentRoute: () => rootRouteImport,
} as any)
const ManagerRoute = ManagerRouteImport.update({
  id: '/manager',
  path: '/manager',
  getParentRoute: () => rootRouteImport,
} as any)
const LocationRequestsRoute = LocationRequestsRouteImport.update({
  id: '/location-requests',
  path: '/location-requests',
  getParentRoute: () => rootRouteImport,
} as any)
const LaborRoute = LaborRouteImport.update({
  id: '/labor',
  path: '/labor',
  getParentRoute: () => rootRouteImport,
} as any)
const InventoryGuideRoute = InventoryGuideRouteImport.update({
  id: '/inventory-guide',
  path: '/inventory-guide',
  getParentRoute: () => rootRouteImport,
} as any)
const InventoryChangesRoute = InventoryChangesRouteImport.update({
  id: '/inventory-changes',
  path: '/inventory-changes',
  getParentRoute: () => rootRouteImport,
} as any)
const InventoryRoute = InventoryRouteImport.update({
  id: '/inventory',
  path: '/inventory',
  getParentRoute: () => rootRouteImport,
} as any)
const IntegrityRoute = IntegrityRouteImport.update({
  id: '/integrity',
  path: '/integrity',
  getParentRoute: () => rootRouteImport,
} as any)
const HrDocumentsRoute = HrDocumentsRouteImport.update({
  id: '/hr-documents',
  path: '/hr-documents',
  getParentRoute: () => rootRouteImport,
} as any)
const HospitalityRoute = HospitalityRouteImport.update({
  id: '/hospitality',
  path: '/hospitality',
  getParentRoute: () => rootRouteImport,
} as any)
const HealthRoute = HealthRouteImport.update({
  id: '/health',
  path: '/health',
  getParentRoute: () => rootRouteImport,
} as any)
const HandbookRoute = HandbookRouteImport.update({
  id: '/handbook',
  path: '/handbook',
  getParentRoute: () => rootRouteImport,
} as any)
const EmailLogRoute = EmailLogRouteImport.update({
  id: '/email-log',
  path: '/email-log',
  getParentRoute: () => rootRouteImport,
} as any)
const DataHealthRoute = DataHealthRouteImport.update({
  id: '/data-health',
  path: '/data-health',
  getParentRoute: () => rootRouteImport,
} as any)
const ChangeLogRoute = ChangeLogRouteImport.update({
  id: '/change-log',
  path: '/change-log',
  getParentRoute: () => rootRouteImport,
} as any)
const CashRoute = CashRouteImport.update({
  id: '/cash',
  path: '/cash',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuditRoute = AuditRouteImport.update({
  id: '/audit',
  path: '/audit',
  getParentRoute: () => rootRouteImport,
} as any)
const ArchiveCenterRoute = ArchiveCenterRouteImport.update({
  id: '/archive-center',
  path: '/archive-center',
  getParentRoute: () => rootRouteImport,
} as any)
const AnalyticsRoute = AnalyticsRouteImport.update({
  id: '/analytics',
  path: '/analytics',
  getParentRoute: () => rootRouteImport,
} as any)
const AlertsRoute = AlertsRouteImport.update({
  id: '/alerts',
  path: '/alerts',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const EmailUnsubscribeRoute = EmailUnsubscribeRouteImport.update({
  id: '/email/unsubscribe',
  path: '/email/unsubscribe',
  getParentRoute: () => rootRouteImport,
} as any)
const LovableEmailSuppressionRoute = LovableEmailSuppressionRouteImport.update({
  id: '/lovable/email/suppression',
  path: '/lovable/email/suppression',
  getParentRoute: () => rootRouteImport,
} as any)
const LovableEmailTransactionalSendRoute =
  LovableEmailTransactionalSendRouteImport.update({
    id: '/lovable/email/transactional/send',
    path: '/lovable/email/transactional/send',
    getParentRoute: () => rootRouteImport,
  } as any)
const LovableEmailTransactionalPreviewRoute =
  LovableEmailTransactionalPreviewRouteImport.update({
    id: '/lovable/email/transactional/preview',
    path: '/lovable/email/transactional/preview',
    getParentRoute: () => rootRouteImport,
  } as any)
const LovableEmailQueueProcessRoute =
  LovableEmailQueueProcessRouteImport.update({
    id: '/lovable/email/queue/process',
    path: '/lovable/email/queue/process',
    getParentRoute: () => rootRouteImport,
  } as any)
const LovableEmailAuthWebhookRoute = LovableEmailAuthWebhookRouteImport.update({
  id: '/lovable/email/auth/webhook',
  path: '/lovable/email/auth/webhook',
  getParentRoute: () => rootRouteImport,
} as any)
const LovableEmailAuthPreviewRoute = LovableEmailAuthPreviewRouteImport.update({
  id: '/lovable/email/auth/preview',
  path: '/lovable/email/auth/preview',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicHooksEmailQaSelftestRoute =
  ApiPublicHooksEmailQaSelftestRouteImport.update({
    id: '/api/public/hooks/email-qa-selftest',
    path: '/api/public/hooks/email-qa-selftest',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicHooksDailyRolloverRoute =
  ApiPublicHooksDailyRolloverRouteImport.update({
    id: '/api/public/hooks/daily-rollover',
    path: '/api/public/hooks/daily-rollover',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicHooksDailyDigestRoute =
  ApiPublicHooksDailyDigestRouteImport.update({
    id: '/api/public/hooks/daily-digest',
    path: '/api/public/hooks/daily-digest',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicHooksArchivePurgeRoute =
  ApiPublicHooksArchivePurgeRouteImport.update({
    id: '/api/public/hooks/archive-purge',
    path: '/api/public/hooks/archive-purge',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicHooksAlertEmailDispatchRoute =
  ApiPublicHooksAlertEmailDispatchRouteImport.update({
    id: '/api/public/hooks/alert-email-dispatch',
    path: '/api/public/hooks/alert-email-dispatch',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/alerts': typeof AlertsRoute
  '/analytics': typeof AnalyticsRoute
  '/archive-center': typeof ArchiveCenterRoute
  '/audit': typeof AuditRoute
  '/auth': typeof AuthRoute
  '/cash': typeof CashRoute
  '/change-log': typeof ChangeLogRoute
  '/data-health': typeof DataHealthRoute
  '/email-log': typeof EmailLogRoute
  '/handbook': typeof HandbookRoute
  '/health': typeof HealthRoute
  '/hospitality': typeof HospitalityRoute
  '/hr-documents': typeof HrDocumentsRoute
  '/integrity': typeof IntegrityRoute
  '/inventory': typeof InventoryRoute
  '/inventory-changes': typeof InventoryChangesRoute
  '/inventory-guide': typeof InventoryGuideRoute
  '/labor': typeof LaborRoute
  '/location-requests': typeof LocationRequestsRoute
  '/manager': typeof ManagerRoute
  '/my-tasks': typeof MyTasksRoute
  '/operations': typeof OperationsRoute
  '/order-guide': typeof OrderGuideRoute
  '/permissions': typeof PermissionsRoute
  '/prep-log': typeof PrepLogRoute
  '/recaps': typeof RecapsRoute
  '/role': typeof RoleRoute
  '/schedule': typeof ScheduleRoute
  '/settings': typeof SettingsRoute
  '/sops': typeof SopsRoute
  '/time-clock': typeof TimeClockRoute
  '/users': typeof UsersRoute
  '/email/unsubscribe': typeof EmailUnsubscribeRoute
  '/lovable/email/suppression': typeof LovableEmailSuppressionRoute
  '/api/public/hooks/alert-email-dispatch': typeof ApiPublicHooksAlertEmailDispatchRoute
  '/api/public/hooks/archive-purge': typeof ApiPublicHooksArchivePurgeRoute
  '/api/public/hooks/daily-digest': typeof ApiPublicHooksDailyDigestRoute
  '/api/public/hooks/daily-rollover': typeof ApiPublicHooksDailyRolloverRoute
  '/api/public/hooks/email-qa-selftest': typeof ApiPublicHooksEmailQaSelftestRoute
  '/lovable/email/auth/preview': typeof LovableEmailAuthPreviewRoute
  '/lovable/email/auth/webhook': typeof LovableEmailAuthWebhookRoute
  '/lovable/email/queue/process': typeof LovableEmailQueueProcessRoute
  '/lovable/email/transactional/preview': typeof LovableEmailTransactionalPreviewRoute
  '/lovable/email/transactional/send': typeof LovableEmailTransactionalSendRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/alerts': typeof AlertsRoute
  '/analytics': typeof AnalyticsRoute
  '/archive-center': typeof ArchiveCenterRoute
  '/audit': typeof AuditRoute
  '/auth': typeof AuthRoute
  '/cash': typeof CashRoute
  '/change-log': typeof ChangeLogRoute
  '/data-health': typeof DataHealthRoute
  '/email-log': typeof EmailLogRoute
  '/handbook': typeof HandbookRoute
  '/health': typeof HealthRoute
  '/hospitality': typeof HospitalityRoute
  '/hr-documents': typeof HrDocumentsRoute
  '/integrity': typeof IntegrityRoute
  '/inventory': typeof InventoryRoute
  '/inventory-changes': typeof InventoryChangesRoute
  '/inventory-guide': typeof InventoryGuideRoute
  '/labor': typeof LaborRoute
  '/location-requests': typeof LocationRequestsRoute
  '/manager': typeof ManagerRoute
  '/my-tasks': typeof MyTasksRoute
  '/operations': typeof OperationsRoute
  '/order-guide': typeof OrderGuideRoute
  '/permissions': typeof PermissionsRoute
  '/prep-log': typeof PrepLogRoute
  '/recaps': typeof RecapsRoute
  '/role': typeof RoleRoute
  '/schedule': typeof ScheduleRoute
  '/settings': typeof SettingsRoute
  '/sops': typeof SopsRoute
  '/time-clock': typeof TimeClockRoute
  '/users': typeof UsersRoute
  '/email/unsubscribe': typeof EmailUnsubscribeRoute
  '/lovable/email/suppression': typeof LovableEmailSuppressionRoute
  '/api/public/hooks/alert-email-dispatch': typeof ApiPublicHooksAlertEmailDispatchRoute
  '/api/public/hooks/archive-purge': typeof ApiPublicHooksArchivePurgeRoute
  '/api/public/hooks/daily-digest': typeof ApiPublicHooksDailyDigestRoute
  '/api/public/hooks/daily-rollover': typeof ApiPublicHooksDailyRolloverRoute
  '/api/public/hooks/email-qa-selftest': typeof ApiPublicHooksEmailQaSelftestRoute
  '/lovable/email/auth/preview': typeof LovableEmailAuthPreviewRoute
  '/lovable/email/auth/webhook': typeof LovableEmailAuthWebhookRoute
  '/lovable/email/queue/process': typeof LovableEmailQueueProcessRoute
  '/lovable/email/transactional/preview': typeof LovableEmailTransactionalPreviewRoute
  '/lovable/email/transactional/send': typeof LovableEmailTransactionalSendRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/alerts': typeof AlertsRoute
  '/analytics': typeof AnalyticsRoute
  '/archive-center': typeof ArchiveCenterRoute
  '/audit': typeof AuditRoute
  '/auth': typeof AuthRoute
  '/cash': typeof CashRoute
  '/change-log': typeof ChangeLogRoute
  '/data-health': typeof DataHealthRoute
  '/email-log': typeof EmailLogRoute
  '/handbook': typeof HandbookRoute
  '/health': typeof HealthRoute
  '/hospitality': typeof HospitalityRoute
  '/hr-documents': typeof HrDocumentsRoute
  '/integrity': typeof IntegrityRoute
  '/inventory': typeof InventoryRoute
  '/inventory-changes': typeof InventoryChangesRoute
  '/inventory-guide': typeof InventoryGuideRoute
  '/labor': typeof LaborRoute
  '/location-requests': typeof LocationRequestsRoute
  '/manager': typeof ManagerRoute
  '/my-tasks': typeof MyTasksRoute
  '/operations': typeof OperationsRoute
  '/order-guide': typeof OrderGuideRoute
  '/permissions': typeof PermissionsRoute
  '/prep-log': typeof PrepLogRoute
  '/recaps': typeof RecapsRoute
  '/role': typeof RoleRoute
  '/schedule': typeof ScheduleRoute
  '/settings': typeof SettingsRoute
  '/sops': typeof SopsRoute
  '/time-clock': typeof TimeClockRoute
  '/users': typeof UsersRoute
  '/email/unsubscribe': typeof EmailUnsubscribeRoute
  '/lovable/email/suppression': typeof LovableEmailSuppressionRoute
  '/api/public/hooks/alert-email-dispatch': typeof ApiPublicHooksAlertEmailDispatchRoute
  '/api/public/hooks/archive-purge': typeof ApiPublicHooksArchivePurgeRoute
  '/api/public/hooks/daily-digest': typeof ApiPublicHooksDailyDigestRoute
  '/api/public/hooks/daily-rollover': typeof ApiPublicHooksDailyRolloverRoute
  '/api/public/hooks/email-qa-selftest': typeof ApiPublicHooksEmailQaSelftestRoute
  '/lovable/email/auth/preview': typeof LovableEmailAuthPreviewRoute
  '/lovable/email/auth/webhook': typeof LovableEmailAuthWebhookRoute
  '/lovable/email/queue/process': typeof LovableEmailQueueProcessRoute
  '/lovable/email/transactional/preview': typeof LovableEmailTransactionalPreviewRoute
  '/lovable/email/transactional/send': typeof LovableEmailTransactionalSendRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/alerts'
    | '/analytics'
    | '/archive-center'
    | '/audit'
    | '/auth'
    | '/cash'
    | '/change-log'
    | '/data-health'
    | '/email-log'
    | '/handbook'
    | '/health'
    | '/hospitality'
    | '/hr-documents'
    | '/integrity'
    | '/inventory'
    | '/inventory-changes'
    | '/inventory-guide'
    | '/labor'
    | '/location-requests'
    | '/manager'
    | '/my-tasks'
    | '/operations'
    | '/order-guide'
    | '/permissions'
    | '/prep-log'
    | '/recaps'
    | '/role'
    | '/schedule'
    | '/settings'
    | '/sops'
    | '/time-clock'
    | '/users'
    | '/email/unsubscribe'
    | '/lovable/email/suppression'
    | '/api/public/hooks/alert-email-dispatch'
    | '/api/public/hooks/archive-purge'
    | '/api/public/hooks/daily-digest'
    | '/api/public/hooks/daily-rollover'
    | '/api/public/hooks/email-qa-selftest'
    | '/lovable/email/auth/preview'
    | '/lovable/email/auth/webhook'
    | '/lovable/email/queue/process'
    | '/lovable/email/transactional/preview'
    | '/lovable/email/transactional/send'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin'
    | '/alerts'
    | '/analytics'
    | '/archive-center'
    | '/audit'
    | '/auth'
    | '/cash'
    | '/change-log'
    | '/data-health'
    | '/email-log'
    | '/handbook'
    | '/health'
    | '/hospitality'
    | '/hr-documents'
    | '/integrity'
    | '/inventory'
    | '/inventory-changes'
    | '/inventory-guide'
    | '/labor'
    | '/location-requests'
    | '/manager'
    | '/my-tasks'
    | '/operations'
    | '/order-guide'
    | '/permissions'
    | '/prep-log'
    | '/recaps'
    | '/role'
    | '/schedule'
    | '/settings'
    | '/sops'
    | '/time-clock'
    | '/users'
    | '/email/unsubscribe'
    | '/lovable/email/suppression'
    | '/api/public/hooks/alert-email-dispatch'
    | '/api/public/hooks/archive-purge'
    | '/api/public/hooks/daily-digest'
    | '/api/public/hooks/daily-rollover'
    | '/api/public/hooks/email-qa-selftest'
    | '/lovable/email/auth/preview'
    | '/lovable/email/auth/webhook'
    | '/lovable/email/queue/process'
    | '/lovable/email/transactional/preview'
    | '/lovable/email/transactional/send'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/alerts'
    | '/analytics'
    | '/archive-center'
    | '/audit'
    | '/auth'
    | '/cash'
    | '/change-log'
    | '/data-health'
    | '/email-log'
    | '/handbook'
    | '/health'
    | '/hospitality'
    | '/hr-documents'
    | '/integrity'
    | '/inventory'
    | '/inventory-changes'
    | '/inventory-guide'
    | '/labor'
    | '/location-requests'
    | '/manager'
    | '/my-tasks'
    | '/operations'
    | '/order-guide'
    | '/permissions'
    | '/prep-log'
    | '/recaps'
    | '/role'
    | '/schedule'
    | '/settings'
    | '/sops'
    | '/time-clock'
    | '/users'
    | '/email/unsubscribe'
    | '/lovable/email/suppression'
    | '/api/public/hooks/alert-email-dispatch'
    | '/api/public/hooks/archive-purge'
    | '/api/public/hooks/daily-digest'
    | '/api/public/hooks/daily-rollover'
    | '/api/public/hooks/email-qa-selftest'
    | '/lovable/email/auth/preview'
    | '/lovable/email/auth/webhook'
    | '/lovable/email/queue/process'
    | '/lovable/email/transactional/preview'
    | '/lovable/email/transactional/send'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRoute
  AlertsRoute: typeof AlertsRoute
  AnalyticsRoute: typeof AnalyticsRoute
  ArchiveCenterRoute: typeof ArchiveCenterRoute
  AuditRoute: typeof AuditRoute
  AuthRoute: typeof AuthRoute
  CashRoute: typeof CashRoute
  ChangeLogRoute: typeof ChangeLogRoute
  DataHealthRoute: typeof DataHealthRoute
  EmailLogRoute: typeof EmailLogRoute
  HandbookRoute: typeof HandbookRoute
  HealthRoute: typeof HealthRoute
  HospitalityRoute: typeof HospitalityRoute
  HrDocumentsRoute: typeof HrDocumentsRoute
  IntegrityRoute: typeof IntegrityRoute
  InventoryRoute: typeof InventoryRoute
  InventoryChangesRoute: typeof InventoryChangesRoute
  InventoryGuideRoute: typeof InventoryGuideRoute
  LaborRoute: typeof LaborRoute
  LocationRequestsRoute: typeof LocationRequestsRoute
  ManagerRoute: typeof ManagerRoute
  MyTasksRoute: typeof MyTasksRoute
  OperationsRoute: typeof OperationsRoute
  OrderGuideRoute: typeof OrderGuideRoute
  PermissionsRoute: typeof PermissionsRoute
  PrepLogRoute: typeof PrepLogRoute
  RecapsRoute: typeof RecapsRoute
  RoleRoute: typeof RoleRoute
  ScheduleRoute: typeof ScheduleRoute
  SettingsRoute: typeof SettingsRoute
  SopsRoute: typeof SopsRoute
  TimeClockRoute: typeof TimeClockRoute
  UsersRoute: typeof UsersRoute
  EmailUnsubscribeRoute: typeof EmailUnsubscribeRoute
  LovableEmailSuppressionRoute: typeof LovableEmailSuppressionRoute
  ApiPublicHooksAlertEmailDispatchRoute: typeof ApiPublicHooksAlertEmailDispatchRoute
  ApiPublicHooksArchivePurgeRoute: typeof ApiPublicHooksArchivePurgeRoute
  ApiPublicHooksDailyDigestRoute: typeof ApiPublicHooksDailyDigestRoute
  ApiPublicHooksDailyRolloverRoute: typeof ApiPublicHooksDailyRolloverRoute
  ApiPublicHooksEmailQaSelftestRoute: typeof ApiPublicHooksEmailQaSelftestRoute
  LovableEmailAuthPreviewRoute: typeof LovableEmailAuthPreviewRoute
  LovableEmailAuthWebhookRoute: typeof LovableEmailAuthWebhookRoute
  LovableEmailQueueProcessRoute: typeof LovableEmailQueueProcessRoute
  LovableEmailTransactionalPreviewRoute: typeof LovableEmailTransactionalPreviewRoute
  LovableEmailTransactionalSendRoute: typeof LovableEmailTransactionalSendRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/users': {
      id: '/users'
      path: '/users'
      fullPath: '/users'
      preLoaderRoute: typeof UsersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/time-clock': {
      id: '/time-clock'
      path: '/time-clock'
      fullPath: '/time-clock'
      preLoaderRoute: typeof TimeClockRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sops': {
      id: '/sops'
      path: '/sops'
      fullPath: '/sops'
      preLoaderRoute: typeof SopsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/schedule': {
      id: '/schedule'
      path: '/schedule'
      fullPath: '/schedule'
      preLoaderRoute: typeof ScheduleRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/role': {
      id: '/role'
      path: '/role'
      fullPath: '/role'
      preLoaderRoute: typeof RoleRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/recaps': {
      id: '/recaps'
      path: '/recaps'
      fullPath: '/recaps'
      preLoaderRoute: typeof RecapsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/prep-log': {
      id: '/prep-log'
      path: '/prep-log'
      fullPath: '/prep-log'
      preLoaderRoute: typeof PrepLogRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/permissions': {
      id: '/permissions'
      path: '/permissions'
      fullPath: '/permissions'
      preLoaderRoute: typeof PermissionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/order-guide': {
      id: '/order-guide'
      path: '/order-guide'
      fullPath: '/order-guide'
      preLoaderRoute: typeof OrderGuideRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/operations': {
      id: '/operations'
      path: '/operations'
      fullPath: '/operations'
      preLoaderRoute: typeof OperationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/my-tasks': {
      id: '/my-tasks'
      path: '/my-tasks'
      fullPath: '/my-tasks'
      preLoaderRoute: typeof MyTasksRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/manager': {
      id: '/manager'
      path: '/manager'
      fullPath: '/manager'
      preLoaderRoute: typeof ManagerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/location-requests': {
      id: '/location-requests'
      path: '/location-requests'
      fullPath: '/location-requests'
      preLoaderRoute: typeof LocationRequestsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/labor': {
      id: '/labor'
      path: '/labor'
      fullPath: '/labor'
      preLoaderRoute: typeof LaborRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/inventory-guide': {
      id: '/inventory-guide'
      path: '/inventory-guide'
      fullPath: '/inventory-guide'
      preLoaderRoute: typeof InventoryGuideRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/inventory-changes': {
      id: '/inventory-changes'
      path: '/inventory-changes'
      fullPath: '/inventory-changes'
      preLoaderRoute: typeof InventoryChangesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/inventory': {
      id: '/inventory'
      path: '/inventory'
      fullPath: '/inventory'
      preLoaderRoute: typeof InventoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/integrity': {
      id: '/integrity'
      path: '/integrity'
      fullPath: '/integrity'
      preLoaderRoute: typeof IntegrityRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/hr-documents': {
      id: '/hr-documents'
      path: '/hr-documents'
      fullPath: '/hr-documents'
      preLoaderRoute: typeof HrDocumentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/hospitality': {
      id: '/hospitality'
      path: '/hospitality'
      fullPath: '/hospitality'
      preLoaderRoute: typeof HospitalityRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/health': {
      id: '/health'
      path: '/health'
      fullPath: '/health'
      preLoaderRoute: typeof HealthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/handbook': {
      id: '/handbook'
      path: '/handbook'
      fullPath: '/handbook'
      preLoaderRoute: typeof HandbookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/email-log': {
      id: '/email-log'
      path: '/email-log'
      fullPath: '/email-log'
      preLoaderRoute: typeof EmailLogRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/data-health': {
      id: '/data-health'
      path: '/data-health'
      fullPath: '/data-health'
      preLoaderRoute: typeof DataHealthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/change-log': {
      id: '/change-log'
      path: '/change-log'
      fullPath: '/change-log'
      preLoaderRoute: typeof ChangeLogRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cash': {
      id: '/cash'
      path: '/cash'
      fullPath: '/cash'
      preLoaderRoute: typeof CashRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/audit': {
      id: '/audit'
      path: '/audit'
      fullPath: '/audit'
      preLoaderRoute: typeof AuditRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/archive-center': {
      id: '/archive-center'
      path: '/archive-center'
      fullPath: '/archive-center'
      preLoaderRoute: typeof ArchiveCenterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/analytics': {
      id: '/analytics'
      path: '/analytics'
      fullPath: '/analytics'
      preLoaderRoute: typeof AnalyticsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/alerts': {
      id: '/alerts'
      path: '/alerts'
      fullPath: '/alerts'
      preLoaderRoute: typeof AlertsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/email/unsubscribe': {
      id: '/email/unsubscribe'
      path: '/email/unsubscribe'
      fullPath: '/email/unsubscribe'
      preLoaderRoute: typeof EmailUnsubscribeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lovable/email/suppression': {
      id: '/lovable/email/suppression'
      path: '/lovable/email/suppression'
      fullPath: '/lovable/email/suppression'
      preLoaderRoute: typeof LovableEmailSuppressionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lovable/email/transactional/send': {
      id: '/lovable/email/transactional/send'
      path: '/lovable/email/transactional/send'
      fullPath: '/lovable/email/transactional/send'
      preLoaderRoute: typeof LovableEmailTransactionalSendRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lovable/email/transactional/preview': {
      id: '/lovable/email/transactional/preview'
      path: '/lovable/email/transactional/preview'
      fullPath: '/lovable/email/transactional/preview'
      preLoaderRoute: typeof LovableEmailTransactionalPreviewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lovable/email/queue/process': {
      id: '/lovable/email/queue/process'
      path: '/lovable/email/queue/process'
      fullPath: '/lovable/email/queue/process'
      preLoaderRoute: typeof LovableEmailQueueProcessRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lovable/email/auth/webhook': {
      id: '/lovable/email/auth/webhook'
      path: '/lovable/email/auth/webhook'
      fullPath: '/lovable/email/auth/webhook'
      preLoaderRoute: typeof LovableEmailAuthWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lovable/email/auth/preview': {
      id: '/lovable/email/auth/preview'
      path: '/lovable/email/auth/preview'
      fullPath: '/lovable/email/auth/preview'
      preLoaderRoute: typeof LovableEmailAuthPreviewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/hooks/email-qa-selftest': {
      id: '/api/public/hooks/email-qa-selftest'
      path: '/api/public/hooks/email-qa-selftest'
      fullPath: '/api/public/hooks/email-qa-selftest'
      preLoaderRoute: typeof ApiPublicHooksEmailQaSelftestRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/hooks/daily-rollover': {
      id: '/api/public/hooks/daily-rollover'
      path: '/api/public/hooks/daily-rollover'
      fullPath: '/api/public/hooks/daily-rollover'
      preLoaderRoute: typeof ApiPublicHooksDailyRolloverRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/hooks/daily-digest': {
      id: '/api/public/hooks/daily-digest'
      path: '/api/public/hooks/daily-digest'
      fullPath: '/api/public/hooks/daily-digest'
      preLoaderRoute: typeof ApiPublicHooksDailyDigestRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/hooks/archive-purge': {
      id: '/api/public/hooks/archive-purge'
      path: '/api/public/hooks/archive-purge'
      fullPath: '/api/public/hooks/archive-purge'
      preLoaderRoute: typeof ApiPublicHooksArchivePurgeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/hooks/alert-email-dispatch': {
      id: '/api/public/hooks/alert-email-dispatch'
      path: '/api/public/hooks/alert-email-dispatch'
      fullPath: '/api/public/hooks/alert-email-dispatch'
      preLoaderRoute: typeof ApiPublicHooksAlertEmailDispatchRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRoute,
  AlertsRoute: AlertsRoute,
  AnalyticsRoute: AnalyticsRoute,
  ArchiveCenterRoute: ArchiveCenterRoute,
  AuditRoute: AuditRoute,
  AuthRoute: AuthRoute,
  CashRoute: CashRoute,
  ChangeLogRoute: ChangeLogRoute,
  DataHealthRoute: DataHealthRoute,
  EmailLogRoute: EmailLogRoute,
  HandbookRoute: HandbookRoute,
  HealthRoute: HealthRoute,
  HospitalityRoute: HospitalityRoute,
  HrDocumentsRoute: HrDocumentsRoute,
  IntegrityRoute: IntegrityRoute,
  InventoryRoute: InventoryRoute,
  InventoryChangesRoute: InventoryChangesRoute,
  InventoryGuideRoute: InventoryGuideRoute,
  LaborRoute: LaborRoute,
  LocationRequestsRoute: LocationRequestsRoute,
  ManagerRoute: ManagerRoute,
  MyTasksRoute: MyTasksRoute,
  OperationsRoute: OperationsRoute,
  OrderGuideRoute: OrderGuideRoute,
  PermissionsRoute: PermissionsRoute,
  PrepLogRoute: PrepLogRoute,
  RecapsRoute: RecapsRoute,
  RoleRoute: RoleRoute,
  ScheduleRoute: ScheduleRoute,
  SettingsRoute: SettingsRoute,
  SopsRoute: SopsRoute,
  TimeClockRoute: TimeClockRoute,
  UsersRoute: UsersRoute,
  EmailUnsubscribeRoute: EmailUnsubscribeRoute,
  LovableEmailSuppressionRoute: LovableEmailSuppressionRoute,
  ApiPublicHooksAlertEmailDispatchRoute: ApiPublicHooksAlertEmailDispatchRoute,
  ApiPublicHooksArchivePurgeRoute: ApiPublicHooksArchivePurgeRoute,
  ApiPublicHooksDailyDigestRoute: ApiPublicHooksDailyDigestRoute,
  ApiPublicHooksDailyRolloverRoute: ApiPublicHooksDailyRolloverRoute,
  ApiPublicHooksEmailQaSelftestRoute: ApiPublicHooksEmailQaSelftestRoute,
  LovableEmailAuthPreviewRoute: LovableEmailAuthPreviewRoute,
  LovableEmailAuthWebhookRoute: LovableEmailAuthWebhookRoute,
  LovableEmailQueueProcessRoute: LovableEmailQueueProcessRoute,
  LovableEmailTransactionalPreviewRoute: LovableEmailTransactionalPreviewRoute,
  LovableEmailTransactionalSendRoute: LovableEmailTransactionalSendRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
