
ALTER TABLE public.inventory_items
  ADD COLUMN IF NOT EXISTS vendor TEXT,
  ADD COLUMN IF NOT EXISTS pack_size TEXT,
  ADD COLUMN IF NOT EXISTS minimum_qty NUMERIC NOT NULL DEFAULT 0,
  ADD COLUMN IF NOT EXISTS preferred_order_qty NUMERIC NOT NULL DEFAULT 0,
  ADD COLUMN IF NOT EXISTS estimated_cost NUMERIC NOT NULL DEFAULT 0,
  ADD COLUMN IF NOT EXISTS last_ordered_at TIMESTAMPTZ,
  ADD COLUMN IF NOT EXISTS last_received_at TIMESTAMPTZ;
